seed: 0
lr: 2.5e-4
critic_lr: 2.5e-4
episode_length: 128
gamma: 0.99
ppo_epoch: 3
gain: 0.01
use_linear_lr_decay: true
use_share_model: true
entropy_coef: 0.01
hidden_size: 512
num_mini_batch: 8
clip_param: 0.2
value_loss_coef: 0.5
max_grad_norm: 10

run_dir: ./run_results/

log_interval: 1
use_recurrent_policy: false
use_valuenorm: true
use_adv_normalize: true

wandb_entity: openrl-lab
experiment_name: atari_ppo

vec_info_class:
  id: "EPS_RewardInfo"